export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  FILL_IN_THE_BLANKS = 'FILL_IN_THE_BLANKS',
  MATCH_THE_PAIRS = 'MATCH_THE_PAIRS',
  TRUE_FALSE = 'TRUE_FALSE',
  DRAG_AND_DROP = 'DRAG_AND_DROP',
  AUDIO_BASED = 'AUDIO_BASED',
  IMAGE_BASED = 'IMAGE_BASED',
  SCENARIO_BASED = 'SCENARIO_BASED',
  TIMED_CHALLENGES = 'TIMED_CHALLENGES',
  MISTAKE_CORRECTION = 'MISTAKE_CORRECTION',
}

